version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /examples/hello-docker
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /deploy/compose
    schedule:
      interval: monthly
